version: '3.9'

services:
  postgres:
    image: postgres:11-alpine
    container_name: library_postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_DB=library
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ./mnt/container_storage/library/progressql
      o: bind

networks:
  backend:
