spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:library}?reWriteBatchedInserts=true
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
      show-sql: true
  liquibase:
    changeLog: classpath:db/changelog/changelog-master.xml
    enabled: true